title: Epic Blog
author: DVD_OSO
email: davidjiang0307@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test site very epic.

# social links
twitter_username: Stuff # DO NOT include the @ character, or else the build will fail!
github_username:  dvd_oso # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
